version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/install_dependencies.sh
      timeout: 300
  BeforeInstall:
    - location: test.sh
      timeout: 300
