version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/install_dependencies.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/dp1.sh
      timeout: 300
  ApplicationStart:
    - location: ./scripts/dp2.sh
      timeout: 300
