version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: test.sh
      timeout: 300
  AfterInstall:
    - location: test2.sh
      timeout: 300
      
      
